### ISSUE TITLE
Can't get this software to work.

### ISSUE THREAD

**Issue by avc1657** [kirksaunders/subtitle-ocr-console#1]
Im just testing now with the english model to see if the software works but I dont really want the bundled en model. I want this one: https://huggingface.co/kha-white/manga-ocr-base/tree/main . Will this model i provided the link for work? I tried it but it doesnt seem to work. Cant get it to work.

**Comment by capnkork** [comment]
The model used in this package is purpose-built, so you can't drop any model in and it work. Even if they had similar architectures, you would need to ensure they had the same input encoding and format.

With some effort, you _could_ reuse the PGS subtitle loading and the SRT output. You would need to write the code that takes the input images (from the PGS loader), re-encodes them in the format the model expects, run them through the model, then plug the results into the SRT encoder. That's basically what I did for the Tesseract support, so you can reference that portion of the code.

On another note, make sure to use the better-results branch. It's slightly cleaner code and has quality of life improvements. I never got around to merging it into mainline.

**Comment by kirksaunders** [comment]
The model used in this package is purpose-built, so you can't drop any model in and it work. Even if they had similar architectures, you would need to ensure they had the same input encoding and format.

With some effort, you could reuse the PGS subtitle loading and the SRT output. You would need to write the code that takes the input images (from the PGS loader), re-encodes them in the format the model expects, run them through the model, then plug the results into the SRT encoder. That's basically what I did for the Tesseract support, so you can reference that portion of the code.

On another note, make sure to use the better-results branch. It's slightly cleaner code and has quality of life improvements. I never got around to merging it into mainline.
